import React from 'react';
import Slide from "react-reveal/Slide"
import './Terms.css';

class Terms extends React.Component {
    render() {
        return (
            <Slide right>
                <div className="terms">
                    <div className="container">
                        <h1>Terms &amp; Conditions</h1>
                        <h4>1. Definitions</h4>
                        <p>In these Terms and Conditions of Sale, "Seller" means Regal Beloit Belgium N.V.; "Buyer" means the person, firm, company or corporation by whom the order is given.</p>
                        <h4>2. THE CONTRACT:</h4>
                        <p>2.1 All orders must be in writing and are accepted subject to these Terms and Conditions of Sale. No terms or conditions put forward by Buyer and no representations, warranties, guarantees or other statements not contained in Seller's quotation or Acknowledgement of Order nor otherwise expressly agreed in writing by Seller shall be binding on Seller.</p>
                        <p>2.2 The Contract shall become effective only upon the date of acceptance of Buyer's order on Seller's Acknowledgement of Order form or upon the date of fulfilment of all conditions precedent stipulated in the Contract, whichever is the later (the "Effective Date "). If the details of the Goods described in Seller's quotation differ from those set out in the Acknowledgement of Order Form the latter shall apply.</p>
                        <p>2.3 No alteration or variation to the Contract shall apply unless agreed in writing by both parties. However, Seller reserves the right to effect minor modifications and/or improvements to the Goods before delivery provided that the performance of the Goods is not adversely affected and that neither the Contract Price nor the delivery date is affected.</p>
                        <h4>3. VALIDITY OF QUOTATION AND PRICES:</h4>
                        <p>3.1 Unless previously withdrawn, Seller's quotation is open for acceptance within the period stated therein or, when no period is so stated, within thirty days after its date.</p>
                        <p>3.2 Prices are firm for delivery within the period stated in Seller's quotation and are exclusive of (a) Value Added Tax and (b) any similar and other t axes, duties, levies or other like charges arising outside Belgium in connection with the performance of the Contract.</p>
                        <p>3.3 Prices (a) are for Goods delivered EXW (Ex works) Seller’s shipping point, exclusive of freight, insurance and handling unless otherwise stated in the Seller's order confirmation.</p>
                        <h4>4. PAYMENT</h4>
                        <p>4.1 Payment shall be made: (a) in full without set-off, counterclaim or withholding of any kind (save where and to the extent that this cannot by law be excluded); and (b) in the currency of Seller's order confirmation within thirty days of date of invoice unless otherwise specified by Seller’s Finance Department. Goods will be invoiced at any time after their readiness for dispatch has been notified to Buyer. Without prejudice to Seller's other rights, Seller reserves the right to: (i)charge interest on any overdue sums at 4% above the base lending rate of Fortis Bank, Brussels (or such higher rate stipulated by applicable law) during the period of delay; (ii) suspend performance of the Contract (including withholding shipment) in the event that Buyer fails or in Seller’s reasonable opinion it appears that Buyer is likely to fail to make payment when due under the Contract or any other contract; and (iii) at any time require such reasonable security for payment as Seller may deem reasonable.</p>
                        <h4>5. DELIVERY PERIOD</h4>
                        <p>5.1 Unless otherwise stated in Seller's order confirmation, all periods stated for delivery or completion run from the Effective Date and are to be treated as estimates only not involving any contractual obligations.</p>
                        <p>5.2 If Seller is delayed in or prevented from performing any of its obligations under the Contract due to the acts or omissions of Buyer or its agents (including but not limited to failure to provide specifications and/or fully dimensioned working drawings and/or such other information as Seller reasonably requires to proceed expeditiously with its obligations under the Contract), the delivery/completion period and the Contract Price shall both be adjusted accordingly.</p>
                        <p>5.3 If delivery is delayed due to any act or omission of Buyer, or if having been notified that the Goods are ready for despatch, Buyer fails to take delivery or provide adequate shipping instructions, Seller shall be entitled to place the Goods into a suitable store at Buyer's expense. Upon placing the Goods into the store, delivery shall be deemed to be complete, risk in the Goods shall pass to Buyer and Buyer shall pay Seller accordingly.</p>
                        <h4>6. FORCE MAJEURE</h4>
                        <p>6.1 Force Majeure of any kind, unforeseeable production, traffic or shipping disturbances, war, acts of terrorism, fire, floods, unforeseeable shortages of labor, utilities or raw materials and supplies, strikes, lockouts, acts of government, and any other hindrances beyond the control of the party obliged to perform which diminish, delay or prevent production, shipment, acceptance or use of the goods, or make it an unreasonable proposition, shall relieve the party from its obligation to supply or take delivery, as the case may be, as long as and to the extent that the hindrance prevails. If, as a result of the hindrance, supply and/or acceptance is delayed by more than eight weeks, either party shall have the right to cancel the contract. Should the Seller’s suppliers fail to supply him in whole or in part , the Seller shall not be under obligation to purchase from other sources. In such cases, the Seller shall have the right to distribute the available quantities among his customers while at the same time taking into account his captive requirements.</p>
                        <h4>7. DELIVERY, RISK &AMP; TITLE</h4>
                        <p>7.1 Unless otherwise expressly stated in the Contract, the Goods will be delivered Ex Works to the destination named in the Contract. Risk of loss of or damage to the Goods shall pass to Buyer upon delivery as aforesaid and Buyer shall be responsible for insurance of the Goods after risk has so passed. Delivery terms used in the Contract shall be defined in accordance with the latest version of Incoterms.</p>
                        <p>7.2 Title to the Goods shall pass to Buyer upon delivery in accordance with Clause 7.1.</p>
                        <p>7.3 Claims for shortfalls in quantity or for incorrect delivery shall be void if made more than 14 days after receipt by the customer.</p>
                        <h4>8. DEFECTS AFTER DELIVERY</h4>
                        <p>8.1 Seller warrants (i) subject to the other provisions of the Contract, good title to and the unencumbered use of the Goods; (ii) that Goods manufactured by Seller and/or Seller’s Affiliates shall conform with Seller's specifications therefore and be free of defects in materials and workmanship. Seller will make good by the supply of a replacement part or parts, any defects which, under proper use, care and maintenance, appear in Goods of Seller’s Affiliates' manufacture and which are reported to Seller within 12 calendar months after their delivery (the "Warranty Period") and which arise solely from faulty materials or workmanship: provided always that defective items are returned to Seller at Buyer’s cost carriage and insurance prepaid within the Warranty Period. Repaired or replacement items will be delivered by Seller at Seller’s cost to Buyer. Goods replaced in accordance with this Clause 10.1 shall be subject to the foregoing warranty for the unexpired portion of the Warranty Period or for ninety days from the date of their return to Buyer (or completion of correction in the case of Services), whichever expires the later.</p>
                        <p>8.2 Notwithstanding Clause 8.1, Seller shall not be liable for any defects caused by: fair wear and tear; materials or workmanship made, furnished or specified by Buyer; non-compliance with Seller's storage, installation, operation or environmental requirements; lack of proper maintenance; any modification or repair not previously authorized by Seller in writing. Seller's costs incurred in investigating and rectifying such defects shall be paid by Buyer upon demand. Buyer shall at all times remain solely responsible for the adequacy and accuracy of all information supplied by it.</p>
                        <p>8.3 Subject to Clause 10.1, the foregoing constitutes Seller's sole warranty and Buyer's exclusive remedy for breach thereof. No representations, warranties or conditions of any kind, express or implied, shall apply as to satisfactory quality, merchantability, fitness for any particular purpose or any other matter with respect to any of the Goods.</p>
                        <h4>9. PATENT, ETV. INFRIGIMENT</h4>
                        <p>9.1 Subject to the limitations set forth in Clause 10, Seller shall indemnify Buyer in the event of any claim for infringement of Letters Patent, Registered Design, Design Right, Trade Mark or Copyright ("Intellectual Property Rights") existing at the date of formation of the Contract arising from the use or sale of the Goods, against all reasonable costs and damages awarded against Buyer in any action for such infringement, or for which Buyer may become liable in any such action, provided always that Seller shall not be liable to so indemnify Buyer in the event that:(i) such infringement arises as a result of Seller having followed a design or instruction furnished or given by Buyer, or the Goods having been used in a manner or for a purpose or in a country not specified by or disclosed to Seller prior to the date of the Contract or in association or combination with any other equipment or software, or (ii) Seller has at its expense procured for Buyer the right to continue to use the Goods or has modified or replaced the Goods so that the Goods no longer infringe. (iii) Buyer has failed to give Seller the earliest possible notice in writing of any claim made or to be made or of any action threatened or brought against Buyer and/or Buyer has failed to permit Seller, at Seller's expense, to conduct and control any litigation that may ensue and all negotiations for a settlement of the claim, or (iv) Buyer has made without Seller's prior written consent any admission which is or may be prejudicial to Seller in respect of any such claim or action, or (v) the Goods have been modified without Seller's prior written authorization.</p>
                        <h4>10. LIMITATION OF LIABILITY</h4>
                        <p>10.1 Maximum aggregate liability for any and all losses, liabilities, expenses (including legal expenses), damages, claims or actions incurred under or in connection with a specific order or a particular blanket order (CALL-OFF order) issued, arising in or by virtue of breach of contract, tort (including negligence), misrepresentation, breach of statutory duty, strict liability, infringement of intellectual property rights or otherwise, shall in no circumstances exceed a sum equal to the total price of the Call -Off in question.</p>
                    </div>
                </div>
            </Slide>
        )
    }
}

export default Terms;